version: '2'
services:
  node:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: node
    volumes:
      - .:/app:delegated
    environment:
      - AMAZEEIO_URL=node.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=3000
      - LAGOON_ROUTE=http://node.docker.amazee.io

networks:
  amazeeio-network:
    external: true
